### PR TITLE
Fixed HEFLO Creator name

### PR DESCRIPTION
**Pull request by HefloRicardo**

### CODE REVIEW

**Comment by dialogik** [comment]
Beside the WHOIS entry I cannot find any information about the provider on the website. Are you an official representative of HEFLO?

**Comment by HefloRicardo** [comment]
Yes i am. Which further information can i provide you to prove?

**Comment by dialogik** [comment]
Could you briefly explain why the name "Venki Tecnologia" cannot be found on the heflo.com contact website (https://www.heflo.com/contact/)?

**Comment by HefloRicardo** [comment]
This is a commercial strategy, Heflo is an international product, the website and the product are in english while the Venki website / other products are in portuguese (That's why we reffer Heflo on Venki website but do not do the opposite). And also Heflo is preparing to be a spinoff from Venki.
If you prefer, i can create a special webpage on heflo.com so you validate the authenticity of the information.

**Comment by dialogik** [comment]
No, your explanation is fine, I'll merge.

But with regards to transparency I recommend to publish the creator/provider of your solution on your website.

Thanks for contributing to this repository.

**Pull request merged**
